### ISSUE TITLE
how to integrate with PARE?

### ISSUE THREAD

**Issue by jinfagang** [InterDigitalInc/UnderPressure#2]
how to integrate with PARE?

**Comment by mourotlucas** [comment]
I'm still not sure to understand your question.

If you mean how to detect contact from a body shape animation instead of a skeletal animation, you could e.g. find SMPL parameters by fitting body mesh, then getting joint angles from using SMPL joint regressor and finally retarget the resulting skeletal animation to any skeleton of our database.
